#!/bin/bash

OPTION="$1"

./qemu/build/qemu-system-aarch64 \
      -machine virt \
      -cpu max,pauth-impdef=on \
      -smp 4 \
      -m 2G \
      -kernel linux/build/arch/arm64/boot/Image \
      -hda buildroot/src/output/images/rootfs.ext3 \
      -append "console=ttyAMA0 root=/dev/vda oops=panic panic_on_warn=1 panic=-1 ftrace_dump_on_oops=orig_cpu debug earlyprintk=serial slub_debug=UZ" \
      -net user,hostfwd=tcp::10023-:22 -net nic \
      -nographic